Config = {}

--------------------------
-- Utility
--------------------------
Config.Utility = {
    CoreName = "qb-core", -- Core Name or Trigger ESX: esx:getSharedObject
    EnableBurn = false, -- Enable burn player?
    Inventory = "qb", -- "qb" or "ox"
    ChanceBurn = 10, -- Chance to burn player
    EnableCustomSounds = true,
    TriggerSound = "InteractSound_SV:PlayOnSource", -- Trigger of custom sound
    Volume = 0.2, -- Volume of custom sound
    Cooldown = true, -- Cooldown?
    CooldownTime = 60000, -- 1 Minute
    Rewards = { -- Only works item's
        Small_MysteryBox = {
            Chance = 10, -- 10% Chance to get rare ITEM
            Normal_Items = {
                [1] = {item = "firework1", amount = math.random(1,2)},
                [2] = {item = "firework2", amount = math.random(1,2)},
                [3] = {item = "firework3", amount = math.random(1,2)},
                [4] = {item = "firework4", amount = math.random(1,2)},
                [5] = {item = "skateboard", amount = math.random(1,2)},
                [6] = {item = "book_batterup", amount = math.random(1,2)},
                [7] = {item = "book_brawler", amount = math.random(1,2)},
                [8] = {item = "book_clothing", amount = math.random(1,2)},
                [9] = {item = "book_enforcer", amount = math.random(1,2)},
                [10] = {item = "book_fireman", amount = math.random(1,2)},
                [11] = {item = "book_heist", amount = math.random(1,2)},
                [12] = {item = "book_hunting", amount = math.random(1,2)},
                [13] = {item = "book_hunting2", amount = math.random(1,2)},
                [14] = {item = "book_hunting3", amount = math.random(1,2)},
                [15] = {item = "book_looter", amount = math.random(1,2)},
                [16] = {item = "book_mining", amount = math.random(1,2)},
                [17] = {item = "book_ranger", amount = math.random(1,2)},
                [18] = {item = "book_stalker", amount = math.random(1,2)},
                [19] = {item = "book_techjunkie", amount = math.random(1,2)},
                [20] = {item = "book_treasurehunt", amount = math.random(1,2)},
                [21] = {item = "book_urbancombat", amount = math.random(1,2)},
                [22] = {item = "toy-egg", amount = math.random(1,2)},
                [23] = {item = "toy-eggg", amount = math.random(1,2)},
                [24] = {item = "barry", amount = math.random(1,2)},
                [25] = {item = "lenny", amount = math.random(1,2)},
                [26] = {item = "oki", amount = math.random(1,2)},
                [27] = {item = "hanno", amount = math.random(1,2)},
                [28] = {item = "muffy", amount = math.random(1,2)},
                [29] = {item = "humpy", amount = math.random(1,2)},
                [30] = {item = "grindy", amount = math.random(1,2)},
                [31] = {item = "lando", amount = math.random(1,2)},
                [32] = {item = "leyla", amount = math.random(1,2)},
                [33] = {item = "meowfurryon", amount = math.random(1,2)},
                [34] = {item = "stagdancer", amount = math.random(1,2)},
                [35] = {item = "sven", amount = math.random(1,2)},
                [36] = {item = "yeager", amount = math.random(1,2)},

            },
            Rare_Items = {
                [1] = {item = "gold_cards", amount = math.random(1,2)},
                [2] = {item = "grandpa_flask", amount = math.random(1,2)},
                [3] = {item = "aincientcoin", amount = math.random(1,2)},
                [4] = {item = "antiquecoin", amount = math.random(1,2)},
                [5] = {item = "goldcoin", amount = math.random(1,2)},
                [6] = {item = "ww2relic", amount = math.random(1,2)},
                [7] = {item = "smokey", amount = math.random(1,2)},
                [8] = {item = "bjorn", amount = math.random(1,2)},
                [9] = {item = "buddha", amount = math.random(1,2)},
                [10] = {item = "clayvon", amount = math.random(1,2)},
                [11] = {item = "donnie", amount = math.random(1,2)},
                [12] = {item = "gloryon", amount = math.random(1,2)},
                [13] = {item = "kiki", amount = math.random(1,2)},
                [14] = {item = "saki", amount = math.random(1,2)},
                [15] = {item = "poopy", amount = math.random(1,2)},
                [16] = {item = "book_sniper", amount = math.random(1,2)},
                [17] = {item = "book_pistol", amount = math.random(1,2)},
                [18] = {item = "book_machinegun", amount = math.random(1,2)},
            }
        },
        Medium_MysteryBox = {
            Chance = 10, -- 10% Chance to get rare ITEM
            Normal_Items = {
                [1] = {item = "firework1", amount = math.random(1,2)},
                [2] = {item = "firework2", amount = math.random(1,2)},
                [3] = {item = "firework3", amount = math.random(1,2)},
                [4] = {item = "firework4", amount = math.random(1,2)},
                [5] = {item = "skateboard", amount = math.random(1,2)},
                [6] = {item = "book_batterup", amount = math.random(1,2)},
                [7] = {item = "book_brawler", amount = math.random(1,2)},
                [8] = {item = "book_clothing", amount = math.random(1,2)},
                [9] = {item = "book_enforcer", amount = math.random(1,2)},
                [10] = {item = "book_fireman", amount = math.random(1,2)},
                [11] = {item = "book_heist", amount = math.random(1,2)},
                [12] = {item = "book_hunting", amount = math.random(1,2)},
                [13] = {item = "book_hunting2", amount = math.random(1,2)},
                [14] = {item = "book_hunting3", amount = math.random(1,2)},
                [15] = {item = "book_looter", amount = math.random(1,2)},
                [16] = {item = "book_mining", amount = math.random(1,2)},
                [17] = {item = "book_ranger", amount = math.random(1,2)},
                [18] = {item = "book_stalker", amount = math.random(1,2)},
                [19] = {item = "book_techjunkie", amount = math.random(1,2)},
                [20] = {item = "book_treasurehunt", amount = math.random(1,2)},
                [21] = {item = "book_urbancombat", amount = math.random(1,2)},
                [22] = {item = "toy-egg", amount = math.random(1,2)},
                [23] = {item = "toy-eggg", amount = math.random(1,2)},
                [24] = {item = "barry", amount = math.random(1,2)},
                [25] = {item = "lenny", amount = math.random(1,2)},
                [26] = {item = "oki", amount = math.random(1,2)},
                [27] = {item = "hanno", amount = math.random(1,2)},
                [28] = {item = "muffy", amount = math.random(1,2)},
                [29] = {item = "humpy", amount = math.random(1,2)},
                [30] = {item = "grindy", amount = math.random(1,2)},
                [31] = {item = "lando", amount = math.random(1,2)},
                [32] = {item = "leyla", amount = math.random(1,2)},
                [33] = {item = "meowfurryon", amount = math.random(1,2)},
                [34] = {item = "stagdancer", amount = math.random(1,2)},
                [35] = {item = "sven", amount = math.random(1,2)},
                [36] = {item = "yeager", amount = math.random(1,2)},
            },
            Rare_Items = {
                [1] = {item = "gold_cards", amount = math.random(1,2)},
                [2] = {item = "grandpa_flask", amount = math.random(1,2)},
                [3] = {item = "aincientcoin", amount = math.random(1,2)},
                [4] = {item = "antiquecoin", amount = math.random(1,2)},
                [5] = {item = "goldcoin", amount = math.random(1,2)},
                [6] = {item = "ww2relic", amount = math.random(1,2)},
                [7] = {item = "smokey", amount = math.random(1,2)},
                [8] = {item = "bjorn", amount = math.random(1,2)},
                [9] = {item = "buddha", amount = math.random(1,2)},
                [10] = {item = "clayvon", amount = math.random(1,2)},
                [11] = {item = "donnie", amount = math.random(1,2)},
                [12] = {item = "gloryon", amount = math.random(1,2)},
                [13] = {item = "kiki", amount = math.random(1,2)},
                [14] = {item = "saki", amount = math.random(1,2)},
                [15] = {item = "poopy", amount = math.random(1,2)},
                [16] = {item = "book_sniper", amount = math.random(1,2)},
                [17] = {item = "book_pistol", amount = math.random(1,2)},
                [18] = {item = "book_machinegun", amount = math.random(1,2)},
            }
        },
        Large_MysteryBox = {
            Chance = 10, -- 10% Chance to get rare ITEM
            Normal_Items = {
                [1] = {item = "firework1", amount = math.random(1,2)},
                [2] = {item = "firework2", amount = math.random(1,2)},
                [3] = {item = "firework3", amount = math.random(1,2)},
                [4] = {item = "firework4", amount = math.random(1,2)},
                [5] = {item = "skateboard", amount = math.random(1,2)},
                [6] = {item = "book_batterup", amount = math.random(1,2)},
                [7] = {item = "book_brawler", amount = math.random(1,2)},
                [8] = {item = "book_clothing", amount = math.random(1,2)},
                [9] = {item = "book_enforcer", amount = math.random(1,2)},
                [10] = {item = "book_fireman", amount = math.random(1,2)},
                [11] = {item = "book_heist", amount = math.random(1,2)},
                [12] = {item = "book_hunting", amount = math.random(1,2)},
                [13] = {item = "book_hunting2", amount = math.random(1,2)},
                [14] = {item = "book_hunting3", amount = math.random(1,2)},
                [15] = {item = "book_looter", amount = math.random(1,2)},
                [16] = {item = "book_mining", amount = math.random(1,2)},
                [17] = {item = "book_ranger", amount = math.random(1,2)},
                [18] = {item = "book_stalker", amount = math.random(1,2)},
                [19] = {item = "book_techjunkie", amount = math.random(1,2)},
                [20] = {item = "book_treasurehunt", amount = math.random(1,2)},
                [21] = {item = "book_urbancombat", amount = math.random(1,2)},
                [22] = {item = "toy-egg", amount = math.random(1,2)},
                [23] = {item = "toy-eggg", amount = math.random(1,2)},
                [24] = {item = "barry", amount = math.random(1,2)},
                [25] = {item = "lenny", amount = math.random(1,2)},
                [26] = {item = "oki", amount = math.random(1,2)},
                [27] = {item = "hanno", amount = math.random(1,2)},
                [28] = {item = "muffy", amount = math.random(1,2)},
                [29] = {item = "humpy", amount = math.random(1,2)},
                [30] = {item = "grindy", amount = math.random(1,2)},
                [31] = {item = "lando", amount = math.random(1,2)},
                [32] = {item = "leyla", amount = math.random(1,2)},
                [33] = {item = "meowfurryon", amount = math.random(1,2)},
                [34] = {item = "stagdancer", amount = math.random(1,2)},
                [35] = {item = "sven", amount = math.random(1,2)},
                [36] = {item = "yeager", amount = math.random(1,2)},
            },
            Rare_Items = {
                [1] = {item = "gold_cards", amount = math.random(1,2)},
                [2] = {item = "grandpa_flask", amount = math.random(1,2)},
                [3] = {item = "aincientcoin", amount = math.random(1,2)},
                [4] = {item = "antiquecoin", amount = math.random(1,2)},
                [5] = {item = "goldcoin", amount = math.random(1,2)},
                [6] = {item = "ww2relic", amount = math.random(1,2)},
                [7] = {item = "smokey", amount = math.random(1,2)},
                [8] = {item = "bjorn", amount = math.random(1,2)},
                [9] = {item = "buddha", amount = math.random(1,2)},
                [10] = {item = "clayvon", amount = math.random(1,2)},
                [11] = {item = "donnie", amount = math.random(1,2)},
                [12] = {item = "gloryon", amount = math.random(1,2)},
                [13] = {item = "kiki", amount = math.random(1,2)},
                [14] = {item = "saki", amount = math.random(1,2)},
                [15] = {item = "poopy", amount = math.random(1,2)},
                [16] = {item = "book_sniper", amount = math.random(1,2)},
                [17] = {item = "book_pistol", amount = math.random(1,2)},
                [18] = {item = "book_machinegun", amount = math.random(1,2)},
            }
        },
    }
}

Language = {
    NoJob = "You don't have the necessary work.",
    NoGang = "You don't have the necessary gang.",
    OpenMystery = "Opening the mystery box...",
    Dead = "You cannot access the mystery box while dead.",
    Water = "You cannot access the mystery box in the water.",
    Wait = "You need to wait to open another mystery box.",
}

